volumes:
  data:

services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
    ports:
      - "${PUBLISHED_PORT}:80"
    environment:
      TZ: America/Sao_Paulo
      CRON_MIN: '2,32'
      BASE_URL: ${BASE_URL}
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
